### ISSUE TITLE
npm run build error tsconfig.js 

### ISSUE THREAD

**Issue by dnaicker** [jolocom/generic-backend#32]
npm run build produces the following errors:
> src/controllers/authentication.ts:19:9 - error TS2322: Type 'string | ParsedQs | string[] | ParsedQs[]' is not assignable to type 'string'.
>   Type 'ParsedQs' is not assignable to type 'string'.
> 
> 19         description
>            ~~~~~~~~~~~
> 
>   node_modules/@jolocom/protocol-ts/dist/lib/interactionTokens.d.ts:100:5
>     100     description: string;
>             ~~~~~~~~~~~
>     The expected type comes from property 'description' which is declared here on type 'WithExtraOptions<ExclusivePartial<IAuthenticationAttrs, "callbackURL">>'
> 
> src/controllers/issuance.ts:20:48 - error TS2339: Property 'split' does not exist on type 'string | ParsedQs | string[] | ParsedQs[]'.
>   Property 'split' does not exist on type 'string[]'.
> 
> 20   const queryTypes: string[] = req.query.types.split(',')
>                                                   ~~~~~
> 
> src/controllers/issuance.ts:22:44 - error TS2339: Property 'split' does not exist on type 'string | ParsedQs | string[] | ParsedQs[]'.
>   Property 'split' does not exist on type 'string[]'.
> 
> 22     req.query.invalid && req.query.invalid.split(',')
>                                               ~~~~~
> 
> src/controllers/issuance.ts:91:44 - error TS2339: Property 'split' does not exist on type 'string | ParsedQs | string[] | ParsedQs[]'.
>   Property 'split' does not exist on type 'string[]'.
> 
> 91     req.query.invalid && req.query.invalid.split(',')
>                                               ~~~~~
> 
> src/controllers/registration.ts:24:48 - error TS2339: Property 'split' does not exist on type 'string | ParsedQs | string[] | ParsedQs[]'.
>   Property 'split' does not exist on type 'string[]'.
> 
> 24   const queryTypes: string[] = req.query.types.split(',')
>                                                   ~~~~~
> 
> src/middleware.ts:21:5 - error TS2322: Type 'JSONWebToken<unknown>' is not assignable to type 'JSONWebToken<JWTEncodable>'.
>   Type 'unknown' is not assignable to type 'JWTEncodable'.
>     Type '{}' is missing the following properties from type 'PaymentResponse': _txHash, txHash, toJSON
> 
> 21     req.userResponseToken = interactionToken
>        ~~~~~~~~~~~~~~~~~~~~~
> 
> 
> Found 6 errors.
> 

changing tsconfig.json to support ES2017 does not alleviate. 

editing the split errors to be (<...> as string).split

**Comment by dnaicker** [comment]
not too sure how to resolve the last error:

    src/middleware.ts:21:5 - error TS2322: Type 'JSONWebToken' is not assignable to type 'JSONWebToken'.
    Type 'unknown' is not assignable to type 'JWTEncodable'.
    Type '{}' is missing the following properties from type 'PaymentResponse': _txHash, txHash, toJSON

    21 req.userResponseToken = interactionToken
    ~~~~~~~~~~~~~~~~~~~~~

    Found 6 errors.

**Comment by mnzaki** [comment]
@dnaicker I haven't yet looked into this error, but we are generally not maintaining this repo very much and this looks like something broke because of a dependency update

are you looking for something specific here or just a general example? have you checked out https://github.com/jolocom/interactions-demo ?

**Comment by dnaicker** [comment]
> @dnaicker I haven't yet looked into this error, but we are generally not maintaining this repo very much and this looks like something broke because of a dependency update
> 
> are you looking for something specific here or just a general example? have you checked out https://github.com/jolocom/interactions-demo ?

Thank you @mnzaki for letting me know. I am trying to create a customisable version of the jolocom interaction demo, where would be a good place to start? Is there perhaps a person, a point of contact or an active community forum where I could post my questions?

**Comment by mnzaki** [comment]
@dnaicker yep there's a gitter chat: https://gitter.im/jolocom/jolocom-sdk
I've also just added a link in the README for future reference :) 

We don't yet have a tutorial or guide about specifically writing a backend application, unfortunately...
This is the currently available documentation for the SDK in general: https://jolocom.github.io/jolocom-sdk/
